# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issue', models.DateTimeField(default=datetime.datetime(2015, 12, 27, 1, 16, 40, 616655))),
                ('date_activate', models.DateTimeField(blank=True, null=True)),
                ('date_end_activate', models.DateTimeField(blank=True, null=True)),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_approval', models.DateTimeField(default=datetime.datetime(2015, 12, 27, 1, 16, 40, 614147))),
                ('series', models.IntegerField(default=1000)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'period',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField()),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purcheses', models.DateTimeField()),
                ('summ_purcheses', models.DecimalField(decimal_places=2, max_digits=11)),
                ('place_purcheses', models.CharField(max_length=100)),
                ('purcheses', models.CharField(max_length=100)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='cards.Cards')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.AddField(
            model_name='issues',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Periods'),
        ),
        migrations.AddField(
            model_name='cards',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Profile'),
        ),
        migrations.AddField(
            model_name='cards',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Issues'),
        ),
        migrations.AddField(
            model_name='cards',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Status'),
        ),
    ]
