# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Status'),
        ),
    ]
