# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 23:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='date_issue',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 27, 1, 19, 20, 77208)),
        ),
        migrations.AlterField(
            model_name='cards',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Profile'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='date_of_approval',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 27, 1, 19, 20, 74760)),
        ),
    ]
