# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'corranswer',
            },
        ),
        migrations.CreateModel(
            name='QuetionsIntelligence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.TextField()),
                ('answer_1', models.TextField()),
                ('answer_2', models.TextField()),
                ('answer_3', models.TextField()),
                ('correct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Correct')),
            ],
            options={
                'db_table': 'intelligence',
            },
        ),
        migrations.CreateModel(
            name='QuetionsMathematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.TextField()),
                ('answer_1', models.TextField()),
                ('answer_2', models.TextField()),
                ('answer_3', models.TextField()),
                ('correct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Correct')),
            ],
            options={
                'db_table': 'mathematic',
            },
        ),
        migrations.CreateModel(
            name='QuetionsPhisical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.TextField()),
                ('answer_1', models.TextField()),
                ('answer_2', models.TextField()),
                ('answer_3', models.TextField()),
                ('correct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Correct')),
            ],
            options={
                'db_table': 'phisical',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('date_passing', models.DateTimeField()),
                ('last_question', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('result_passing', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'result_test',
            },
        ),
        migrations.CreateModel(
            name='TestsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'testslist',
            },
        ),
    ]
